spring:
  application:
    name: springboot-aws-demo

  datasource:
    url: jdbc:mysql://testdb.clcw6ey6ky41.ap-south-1.rds.amazonaws.com:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: hogg2695

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
